Id b 5
OlegVorontsov/P2Project pull request #10
Opened 2024-11-11 15:12 UTC by OlegVorontsov

2024-11-11 15:23 UTC, Asasen1 requested changes
По заданию не увидел преобразование реквестов в комманды.

2024-11-11 15:23 UTC, Asasen1 commented on Backend/src/P2Project.Application/Volunteers/CreateVolunteer/CreateVolunteerHandler.cs
> +            // assistanceDetails
Ничего против комментариев не имею, но в данном случае мне кажется они бесполезны

2024-11-12 16:23 UTC, KirillSachkov requested changes
как поправишь, можно мержить

2024-11-12 16:23 UTC, KirillSachkov commented on Backend/src/P2Project.Application/Volunteers/ICommand.cs
> +namespace P2Project.Application.Volunteers
этот интерфейс нужно положить в общую папку, не volunteers

2024-11-13 05:03 UTC, merged