Id b 6
OlegVorontsov/P2Project pull request #16
Opened 2024-11-14 15:32 UTC by OlegVorontsov

Нахожусь в процессе добавления фичей по обновлению волонтера. Есть вопросы по maininfo:
1. на каком этапе создавать команду. пока сделал так
![1](https://github.com/user-attachments/assets/399ef9e9-267a-4004-94e4-60c77163d5ed)
2. нужно ли делать обновление email

2024-11-15 11:24 UTC, KirillSachkov commented
> Нахожусь в процессе добавления фичей по обновлению волонтера. Есть вопросы по maininfo:
> 
>     1. на каком этапе создавать команду. пока сделал так
>        ![1](https://private-user-images.githubusercontent.com/102809790/386257425-399ef9e9-267a-4004-94e4-60c77163d5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzAwOTgsIm5iZiI6MTczMTY2OTc5OCwicGF0aCI6Ii8xMDI4MDk3OTAvMzg2MjU3NDI1LTM5OWVmOWU5LTI2N2EtNDAwNC05NGU0LTYwYzc3MTYzZDVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxMTIzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGYyYjY3OGNiMTcxYTI1OTBjNTRhMGRkMzI4MTBmMzkxNzI4ZDBjMGQ2Mjg0YmYxZjZjYjY3MzdjZjgwNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CM0xquLje_zhvfbsJ3kI1XN0SJpuzA6JKjJ21W2BDkE)
> 
>     2. нужно ли делать обновление email

комманду нужно создавать в слое API, когда ты получаешь запрос в контроллере и перед тем, как вызываешь бизнес логику. Обновлять email не нужно пока

2024-11-15 11:26 UTC, KirillSachkov requested changes

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.API/.config/dotnet-tools.json
> +  "version": 1,
вот этого файла не должно быть, надо проверить gitignore

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.API/Controllers/VolunteerController.cs
> +
вот здесь хорошо было бы комманду создавать

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.Application/Volunteers/Delete/DeleteHandler.cs
> +    }
тут нужны отступы

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.Application/Volunteers/Delete/DeleteHandler.cs
> +    public record DeleteRequest(Guid VolunteerId);
request нужно хранить в слое с API, а комманды в application

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.Application/Volunteers/Delete/DeleteHandler.cs
> +    public record DeleteRequest(Guid VolunteerId);
во всех остальных фичах аналогично

2024-11-15 11:26 UTC, KirillSachkov commented on Backend/src/P2Project.API/Properties/serviceDependencies.local.json
> +  "dependencies": {}
вот этого всего в репе быть не должно, нужно поправить gitiignore

2024-11-16 08:30 UTC, OlegVorontsov commented on Backend/src/P2Project.API/.config/dotnet-tools.json
> +  "version": 1,
поправил

2024-11-16 08:30 UTC, OlegVorontsov commented on Backend/src/P2Project.API/Controllers/VolunteerController.cs
> +
поправил

2024-11-16 08:30 UTC, OlegVorontsov commented on Backend/src/P2Project.Application/Volunteers/Delete/DeleteHandler.cs
> +    }
поправил

2024-11-16 08:30 UTC, OlegVorontsov commented on Backend/src/P2Project.Application/Volunteers/Delete/DeleteHandler.cs
> +    public record DeleteRequest(Guid VolunteerId);
сделал

2024-11-16 08:31 UTC, OlegVorontsov commented on Backend/src/P2Project.API/Properties/serviceDependencies.local.json
> +  "dependencies": {}
поправил

2024-11-16 08:31 UTC, OlegVorontsov commented
задание Б-6 сделал

2024-11-16 10:39 UTC, KirillSachkov requested changes

2024-11-16 10:39 UTC, KirillSachkov commented on Backend/src/P2Project.API/Controllers/VolunteerController.cs
> +                return dtoValidationResult.ToValidationErrorResponse();
Тебе нужно валидировать всё за один раз, где-то ты значит неверно настроил валидатор. Можно сделать так, что у тебя есть вложенния Dto и она будет валидироваться, когда ты вызываешь валидацию у UpdateSocialNetworksRequest

2024-11-16 10:39 UTC, KirillSachkov commented on Backend/src/P2Project.API/Controllers/VolunteerController.cs
> +                return dtoValidationResult.ToValidationErrorResponse();
тоже самое

2024-11-16 14:09 UTC, KirillSachkov approved these changes

2024-11-16 14:14 UTC, merged